---
# tasks file for mysql_db
    - name: Install MysQL database
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start database service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create application database
      mysql_db: login_unix_socket=/var/run/mysqld/mysqld.sock name={{ db_name }} state=present

    - name: Create database user
      mysql_user: login_unix_socket=/var/run/mysqld/mysqld.sock name={{ db_user }} password={{ db_password }} priv='*.*:ALL' state=present host='%'
